name = "school-lunch-worker"
compatibility_date = "2023-12-01"

[vars]
WEBHOOK_URL = "<WEBHOOK_URL>"
R2_URL = "<R2_URL>"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "handa-kyushoku-image"


[triggers]

crons = ["0 4 * * 1-5"]